# Generated by Django 5.2.4 on 2025-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KerogenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.TextField(db_comment="年份")),
                ("author", models.TextField(db_comment="作者")),
                ("kerogen_type", models.TextField(db_comment="干酪根类型")),
                ("kerogen_name", models.TextField(db_comment="干酪根名称")),
                (
                    "Kerogen_shale_molecular_formula",
                    models.TextField(
                        blank=True, db_comment="干酪根/页岩结构分子式", null=True
                    ),
                ),
                (
                    "literature_source",
                    models.TextField(blank=True, db_comment="文献来源", null=True),
                ),
                (
                    "model_element_ratio_H_C",
                    models.TextField(blank=True, db_comment="模型元素比H/C", null=True),
                ),
                (
                    "model_element_ratio_O_C",
                    models.TextField(blank=True, db_comment="模型元素比O/C", null=True),
                ),
                (
                    "model_element_ratio_N_C",
                    models.TextField(blank=True, db_comment="模型元素比N/C", null=True),
                ),
                (
                    "model_element_ratio_S_C",
                    models.TextField(blank=True, db_comment="模型元素比S/C", null=True),
                ),
                (
                    "experimental_kerogen_density",
                    models.TextField(
                        blank=True,
                        db_comment="实验干酪根的物理性质:实验干酪根密度",
                        null=True,
                    ),
                ),
                (
                    "simulated_kerogen_density",
                    models.CharField(
                        blank=True,
                        db_comment="干酪根模型的物理性质:模拟干酪根密度",
                        null=True,
                    ),
                ),
                (
                    "molecular_model_of_2d_kerogen",
                    models.FileField(
                        blank=True,
                        db_comment="二维干酪根分子模型",
                        null=True,
                        upload_to="kerogen_model/",
                    ),
                ),
            ],
        ),
    ]
