# Generated by Django 5.2.4 on 2025-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kerogenmodel",
            name="Kerogen_shale_molecular_formula",
            field=models.TextField(
                blank=True, help_text="干酪根/页岩结构分子式", null=True
            ),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="author",
            field=models.TextField(help_text="作者"),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="experimental_kerogen_density",
            field=models.TextField(
                blank=True, help_text="实验干酪根的物理性质:实验干酪根密度", null=True
            ),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="kerogen_name",
            field=models.TextField(help_text="干酪根名称"),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="kerogen_type",
            field=models.TextField(help_text="干酪根类型"),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="literature_source",
            field=models.TextField(blank=True, help_text="文献来源", null=True),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="model_element_ratio_H_C",
            field=models.TextField(blank=True, help_text="模型元素比H/C", null=True),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="model_element_ratio_N_C",
            field=models.TextField(blank=True, help_text="模型元素比N/C", null=True),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="model_element_ratio_O_C",
            field=models.TextField(blank=True, help_text="模型元素比O/C", null=True),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="model_element_ratio_S_C",
            field=models.TextField(blank=True, help_text="模型元素比S/C", null=True),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="molecular_model_of_2d_kerogen",
            field=models.FileField(
                blank=True,
                help_text="二维干酪根分子模型",
                null=True,
                upload_to="kerogen_model/",
            ),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="simulated_kerogen_density",
            field=models.CharField(
                blank=True, help_text="干酪根模型的物理性质:模拟干酪根密度", null=True
            ),
        ),
        migrations.AlterField(
            model_name="kerogenmodel",
            name="year",
            field=models.TextField(help_text="年份"),
        ),
    ]
