/*
Navicat MySQL Data Transfer

Source Server         : localhost1
Source Server Version : 80025
Source Host           : localhost:3306
Source Database       : kerogen

Target Server Type    : MYSQL
Target Server Version : 80025
File Encoding         : 65001

Date: 2025-07-06 23:21:39
*/

-- SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `api_kerogenmodel`
-- ----------------------------
DROP TABLE IF EXISTS `api_kerogenmodel`;
-- CREATE TABLE `api_kerogenmodel` (
--   `Year` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
--   `Author` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
--   `Keragen type` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
--   `Kerogen name` varchar(580) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
--   `Kerogen/shale molecular formula` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Literature source` varchar(600) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Model element ratio H/C` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Model element ratio O/C` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Model element ratio N/C` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Model element ratio S/C` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Experimental kerogen density` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   `Simulated kerogen density` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
--   PRIMARY KEY (`Year`,`Author`,`Keragen type`,`Kerogen name`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE api_kerogenmodel (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  Year TEXT NOT NULL,
  Author TEXT NOT NULL,
  "Keragen type" TEXT NOT NULL,
  "Kerogen name" TEXT NOT NULL,
  "Kerogen/shale molecular formula" TEXT,
  "Literature source" TEXT,
  "Model element ratio H/C" TEXT,
  "Model element ratio O/C" TEXT,
  "Model element ratio N/C" TEXT,
  "Model element ratio S/C" TEXT,
  "Experimental kerogen density" TEXT,
  "Simulated kerogen density" TEXT,
  PRIMARY KEY (Year, Author, "Keragen type", "Kerogen name")
);
-- ----------------------------
-- Records of api_kerogenmodel
-- ----------------------------

("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density")

INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1969', 'Burlingame', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', '干酪根的取代基结构（所示的干酪根不具有除作为区域外的主体干酪根，但类似地具有附着于主体干酪根的官能团）', 'Fatty Acids Derived from the Green River Formation Oil Shale by Extractions and Oxidations — A Review', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1969', 'Robinson', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', 'C215H330O12N5S（经验化学式）', '1、Kerogen of the Green River Formation.   2、Isolation Procedures for Kerogens and Associated Soluble Organic Materials', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1971', 'Djuricic', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', '干酪根网络的亚结构单元', 'Organic acids obtained by alkaline permanganate oxidation of kerogen from the Green River (Colorado) shale', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1974', 'Schmidt-Collerus、Prien', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', '干酪根聚合物的亚结构单元和“stick figure” model', '1、Investigations of the hydrocarbon structure of kerogen from oil shale of the Green River formation           2、2011-Hillier-Pyrolysis kinetics and chemical structure considerations of a Green River oil shale and its derivatives             3、1976-Yen-Structural Aspects of Organic Components in Oil Shales', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1974、1976', 'Yen', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', 'C235H397O13N3S5（“stick figure” model即“棒状图形”模型，显示了一个带有基本成分的假设结构', 'Structural Aspects of Organic Components in Oil Shales', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ("1975、1984", "Tissot、Welte", 'Ⅱ型', '未成熟干酪根/低演化阶段', '非通常的结构表现形式，具体后续考虑', "1、L'evolution thermique de la matière organique des sédiments : applications d'une simulation mathématique. Potentiel pétrolier des bassins sédimentaires de reconstitution de l'histoire thermique des sédiments       2、Petroleum formation and occurrence【P147】", '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1975、1984', 'Tissot、Welte', 'Ⅱ型', '通过深成热解作用进入高演化阶段', '非通常的结构表现形式，具体后续考虑', "1、L'evolution thermique de la matière organique des sédiments : applications d'une simulation mathématique. Potentiel pétrolier des bassins sédimentaires de reconstitution de l'histoire thermique des sédiments       2、Petroleum formation and occurrence【P147】", '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1977', 'Young, Yen', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', '“棒状图形”模型，绿河干酪根的假设结构', 'The nature of straight-chain aliphatic structures in green river kerogen', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1980', 'Durand', 'Ⅰ型和Ⅱ型', '', '', 'Kerogen: Insoluble organic matter from sedimentary rocks（未找到书籍）', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1980', 'Oberlin', 'Ⅱ型', '深成热解阶段的开始（Oberlin et al. [15] generated a Kuckersite model (a rare type II kerogen that is ‘‘bituminous’’ in nature) with artistic flair, for the first time representing a coal as an assemblage of smaller fragments with strong relationship to their organic precursors. It also captured the phenomenon of aromatic (p–p) stacking which Meyers also captured [18]. 【2012-Mathews-The molecular representations of coal – A review】）', '非通常的结构表现形式，具体后续考虑', '1、Electron microscopic study of kerogen microtexture. Selected criteria for determining the evolution path and evolution stage of kerogen         2、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1984、1986', '秦匡宗', '未成熟Ⅰ型', '抚顺干酪根', 'C312H468O16N7S2', '1、1982-超临界流体抽提法研究茂名与抚顺油页岩中油母质的化学结构(Ⅱ)——抽提产物的性质及油母质化学结构的初步探讨   2、Chemical Structure Investigation of Maoming Oil Shale Kerogen by Supercritical Gas Extraction     2、茂名和抚顺油页岩组成结构的研究Ⅰ.有机质的芳碳结构      3、茂名和抚顺油页岩组成结构的研究——Ⅲ.有机质的平均结构单元', '1.5', '0.0513', '0.0224', '0.0064', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1984、1986', '秦匡宗', '未成熟Ⅰ型', '茂名干酪根', 'C302H440O23N6S2', '1、1982-超临界流体抽提法研究茂名与抚顺油页岩中油母质的化学结构(Ⅱ)——抽提产物的性质及油母质化学结构的初步探讨   2、Chemical Structure Investigation of Maoming Oil Shale Kerogen by Supercritical Gas Extraction     2、茂名和抚顺油页岩组成结构的研究Ⅰ.有机质的芳碳结构      3、茂名和抚顺油页岩组成结构的研究——Ⅲ.有机质的平均结构单元', '1.457', '0.0762', '0.0199', '0.0066', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1985', 'McGowan', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', 'C112H179K5NO3S【K意思是K元素还是可连接的部分，之后看】【根据高氯酸氧化反应的结果提出了一个模型，需要画出才知道分子式，但是Chemdraw和MS中的分子式不一样】', 'A comparison of the dissolution of model compounds and the kerogen of Green River oil shale by oxidation with perchloric acid — A model for the kerogen of Green River oil shale', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅲ型', 'III-A；喀麦隆杜阿拉盆地上白垩统沉积岩-成岩阶段开始', 'C1443', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅲ型', 'III-B；喀麦隆杜阿拉盆地上白垩统沉积岩-深成变质阶段开始', 'C1215', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅲ型', 'III-C；喀麦隆杜阿拉盆地上白垩统沉积岩-深成变质阶段末期', 'C948 【C993 H676 N9 O59 S6，MS中显示的H比chemdraw中的多1个；与文献给出的H/C、O/C和MW不一致,】', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅱ型', 'II-A；法国下托阿尔统页岩-成岩阶段开始', 'C1505', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅱ型', 'II-B；法国下托阿尔统页岩-深成变质阶段开始', 'C1285【C1294 H1616 Mg N15 O112 S23】', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅱ型', 'II-C；法国下托阿尔统页岩-深成变质阶段末期', 'C569 【实际画出来C575 H436 N8 O17 S11，与文献给出的H/C、O/C和MW不一致】', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅰ型', 'I-A；Green River绿河油页岩干酪根-成岩阶段开始', 'C1439 【C1430 H2415 Mg N5 O88 S2】待检查', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1987、2003、2007', 'Behar、Vandenbroucke', 'Ⅰ型', 'I-C；Green River绿河油页岩干酪根-深成变质阶段末期', 'C305   【实际C307 H255 N O4 S，比师兄发的少个CH5，已经在二维中将区别标注出】', '1、1987-Behar、Vandenbroucke-Chemical modelling of kerogens            2、 2003-Kerogen: from Types to Models of Chemical Structure                 3、Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1990', 'Faulon', 'Ⅲ型', '成岩阶段开始', 'C873H899O358N13', '3D Chemical model for geological macromolecules', '1.0298', '0.0401', '0.0149', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1991', 'Stanton、McGowan', '', 'Chattanooga油页岩干酪根（与1985-McGowan-A comparison of the dissolution of model compounds and the kerogen of Green River oil shale by oxidation with perchloric acid — A model for the kerogen of Green River oil shale绿河油页岩干酪根模型做比较）', 'C161H212O3', 'The characterization of the kerogen of Chattanooga oil shale. Part II — Analysis of oxidation products and proposal of a model for the structure of kerogen in Chattanooga oil shale', '1.3168', '0.0186', '0', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1995', 'Siskin', '', '澳大利亚昆士兰Rundle Ramsay Crossing油页岩干酪根 ', 'C651H1086O61N14S4（O的个数不对，查分子式的出处，看是不是记录错了）【画出的结构为C651 H1090 O62 N14 S4】', '1、1995-Siskin-Detailed structural characterization of the organic material in Rundle Ramsay Crossing and Green River oil shales          2、2007-Vandenbroucke-Kerogen origin, evolution and structure', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('1995', 'Siskin', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', 'C645H1017O17N19S4（画出不是这个分子式，这个是模型修改后的）', '1、1995-Siskin-Detailed structural characterization of the organic material in Rundle Ramsay Crossing and Green River oil shales          2、2007-Vandenbroucke-Kerogen origin, evolution and structure', '', '', '', '', '0.95 g/cm3', '2011-Facelli-Atomistic modeling of oil shale kerogens and asphaltenes along with their interactions with the inorganic mineral matrix    12个干酪根分子组成的晶胞优化后的密度为0.90 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2003', 'Lille', 'Ⅱ/Ⅰ型(2012,Ru；2011,Tong；2013，Orendt；2019-Chu, WenyⅠng)', '爱沙尼亚kukersite干酪根', 'C421H638O44S4NCl（经验公式，实际画出来和2014-Lille的公式一样，检查一下）', '1、Molecular model of Estonian kukersite kerogen evaluated by 13C MAS NMR spectra      2、2003-Lille-CURRENT KNOWLEDGE ON THE ORIGIN AND STRUCTURE OF ESTONIAN KUKERSITE KEROGEN', '1.515', '0.1045', '0.00237', '0.0095', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2004', 'Kelemen、Siskin', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', '', 'Organic mater models of oil shale revisited', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2004', 'Lille', 'Ⅱ/Ⅰ型(2012,Ru；2011,Tong；2013，Orendt；2019-Chu, WenyⅠng)', '爱沙尼亚kukersite干酪根', 'C420H634O44NS4Cl', 'BEHAVIOR OF ESTONIAN KUKERSITE KEROGEN IN MOLECULAR MECHANICAL FORCE FIELD', '1.5095', '0.1048', '0.0024', '0.0095', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2007', 'Freund', 'Ⅱ型', '具有代表性的小的CHO模型', 'C75H100O6【有可连接部分】', '', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2007', 'Freund', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', 'C194H267N5O7S【有可连接部分】（Fruend 模型是10000个核中的8个）', 'Predicting oil and gas compositional yields via chemical structure–chemical yield modeling (CS-CYM): Part 1 – Concepts and implementation', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2009', 'Zhang Lu', 'Ⅰ型', 'Green River绿河油页岩干酪根-成岩阶段开始（基于1987,-Behar的进行修改），实验数据基于LeBoeuf, E.J., Weber, W.J., 2000. Macromolecular characteristics of natural organic matter. 1. Insights from glass transition and enthalpic relaxation behavior. Environmental Science and Technology 34, 3623–3631.', '', 'A molecular dynamics study of natural organic matter: 1. Lignin, kerogen and soot', '', '', '', '', '1.11  g/cm3', '25 °C 时0.93 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2011', 'Julio C.Facelli', 'Ⅰ型', 'Green River绿河油页岩干酪根', 'C647H1017O17N19S4', 'ATOMISTIC MODELING OF OIL SHALE KEROGENS AND ASPHALTENES ALONG WITH THEIR INTERACTIONS WITH THE INORGANIC MINERAL MATRIX', '1.5718', '0.0263', '0.0294', '0.0062', '0.95 g/cm3', '0.90 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2012、2013', '茹鑫', '未成熟Ⅰ型', '桦甸油页岩干酪根', 'C243H407N3O25S2', '2012、2013-Ru Xin', '1.674897', '0.10288', '0.0123456', '0.00823045', '0.95g/cc=0.95g/cm3 （在20 °C）', '最低总能量下的密度0.93g/cc=0.93g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2013', 'Orendt ', 'Ⅰ型', '美国科罗拉多州Green River绿河油页岩干酪根', 'C645H1017O17N19S4（由七个独立的片段组成）', '2013-Orendt-Three-dimensional structure of the Siskin Green River oil shale kerogen model: A comparison between calculated and observed properties. ', '1.5718', '0.0263', '0.0294', '0.0062', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2013', 'Yiannourakou', 'Ⅱ', '成熟干酪根模型（通过虚拟粒子模拟了微孔1.4 nm（<2 nm））深成热解阶段末期，研究了甲烷在干酪根孔隙中的吸附', '总原子数约150', 'Molecular simulation of adsorption in microporous materials', '', '', '', '', '参考文献中成熟干酪根的密度变化在 1.2 to 1.4 g/cm3', '平均1.3 g/cm3±0.05');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2014', 'Collell', '', '基于2013-Yiannourakou的模型构建含有8个干酪根分子（文章有干酪根分子结构）的微孔结构（模拟了5 种结构，其虚拟粒子直径值从 9 到 17 Å 不等，得到对应的的模型的孔隙体积等数值），模拟甲烷/乙烷混合吸附', '无分子式', '2014-Collell-Molecular simulation and modelisation of methane/ethane mixtures adsorption onto a microporous molecular model of kerogen under typical reservoir conditions', '', '', '', '', '参考文献中成熟干酪根的密度变化在 1.2 to 1.4 g/cm3', '典型的油藏条件(338 K, 20 MPa)下得到1.24 g/cm3  ');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2014', '曹旭辉', 'Ⅰ', '未知', 'C415H698O22', '甲烷在干酪根中吸附的巨正则Monte Carlo模拟研究', '1.68', '0.053', '0', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2014', '曹旭辉', 'Ⅱ-Ⅲ', '未知', 'C406H528O19', '甲烷在干酪根中吸附的巨正则Monte Carlo模拟研究', '1.3', '0.047', '0', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2014', '曹旭辉', 'Ⅲ/Ⅳ', '未知', 'C128H68O7', '甲烷在干酪根中吸附的巨正则Monte Carlo模拟研究', '0.53', '0.055', '0', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Guan', 'Ⅰ型', '桦甸油页岩干酪根', 'C235H365O25N3S3（设计了10个同分异构体，最终选择了网格数为11的S10模型，进一步讨论了取代基位置对于S10模型稳定性的影响，共19个，最终选择S10的T4作为模型）', '2015-Guan-Three-Dimensional Structure of a Huadian Oil Shale Kerogen Model: An Experimental and Theoretical Study', '1.5532', '0.0553', '0.0128', '0.0128', '', '建立的二维干酪根模型中没有使用密度来验证模型，仅是利用核磁图谱相近而验证。');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Ungerer', 'Ⅰ-A', '未成熟Green River绿河油页岩干酪根', 'C251H385O13N7S3', '2014-Collell-Molecular Simulation of Bulk Organic Matter in Type II Shales in the Middle of the Oil Formation Window           2015-Ungerer-Molecular Modeling of the Volumetric and Thermodynamic Properties of Kerogen: Influence of Organic Type and Maturity', '1.53', '0.052', '0.028', '0.012', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Ungerer', 'Ⅱ-A', '未成熟Duvernay干酪根', 'C252H294O24N6S3', '2014-Collell-Molecular Simulation of Bulk Organic Matter in Type II Shales in the Middle of the Oil Formation Window           2015-Ungerer-Molecular Modeling of the Volumetric and Thermodynamic Properties of Kerogen: Influence of Organic Type and Maturity', '1.17', '0.095', '0.024', '0.012', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Ungerer', 'Ⅱ-B', '油窗顶部Duvernay干酪根', 'C234H263O14N5S2', '2014-Collell-Molecular Simulation of Bulk Organic Matter in Type II Shales in the Middle of the Oil Formation Window           2015-Ungerer-Molecular Modeling of the Volumetric and Thermodynamic Properties of Kerogen: Influence of Organic Type and Maturity', '1.12', '0.06', '0.022', '0.009', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Ungerer', 'Ⅱ-C', '油窗中-末期Duvernay干酪根', 'C242H219O13N5S2', '2014-Collell-Molecular Simulation of Bulk Organic Matter in Type II Shales in the Middle of the Oil Formation Window           2015-Ungerer-Molecular Modeling of the Volumetric and Thermodynamic Properties of Kerogen: Influence of Organic Type and Maturity', '0.905', '0.054', '0.021', '0.008', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Ungerer', 'Ⅱ-D', '过成熟Duvernay干酪根', 'C175H102O9N4S2', '2014-Collell-Molecular Simulation of Bulk Organic Matter in Type II Shales in the Middle of the Oil Formation Window           2015-Ungerer-Molecular Modeling of the Volumetric and Thermodynamic Properties of Kerogen: Influence of Organic Type and Maturity', '0.58', '0.051', '0.023', '0.011', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2015', 'Ungerer', 'Ⅲ-A', '未成熟亚洲地区Gippsland干酪根', 'C233H204O27N4', '2014-Collell-Molecular Simulation of Bulk Organic Matter in Type II Shales in the Middle of the Oil Formation Window           2015-Ungerer-Molecular Modeling of the Volumetric and Thermodynamic Properties of Kerogen: Influence of Organic Type and Maturity', '0.886', '0.116', '0.017', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2016', 'Bousige', ' Ⅱ', 'EFK：an immature marine (Type II) kerogen from the carbonate-rich Eagle Ford Play【Eagle Ford Play中的未成熟海相(II型)干酪根】-%Ro=0.65', '未知', 'Realistic molecular model of kerogen’s nanostructure', '1.19', '0.1', '', '', '0.8 to 2.2 g/cm3', '1.2 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2016', 'Bousige', ' Ⅱ', 'MarK：a mature marine kerogen (Type II) from the clay-rich Marcellus Play-%Ro=2.2', '未知', 'Realistic molecular model of kerogen’s nanostructure', '0.46', '0.11', '', '', '0.8 to 2.2 g/cm3', '1.2 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2016', 'Bousige', 'Ⅱ-S', 'MEK：an immature sulphur-rich marine (Type II-S) kerogen from the Middle East-%Ro=0.55', '未知', 'Realistic molecular model of kerogen’s nanostructure', '1.45', '0.08', '', '', '0.8 to 2.2 g/cm3', '1.2 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2016', 'Bousige', '实际不是干酪根', 'PY02：A mineral-free shungite (PY02), a rather exceptional kerogen type from Russia,次石墨', '未知', 'Realistic molecular model of kerogen’s nanostructure', '0.09', '0.01', '', '', '0.8 to 2.2 g/cm3', '1.2 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2016', 'TongJiahui', 'Ⅰ型', '桦甸油页岩干酪根', 'C387H683O30N5S4', '1、Evaluation of Structural Characteristics of Huadian Oil Shale Kerogen Using Direct Techniques (Solid-State 13C NMR, XPS, FT-IR, and XRD)           2、2016-Tong Jianhui-Evaluation of the macromolecular structure of Huadian oil shale kerogen using molecular modeling', '1.76', '0.078', '0.013', '0.01', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Gao Yuan', 'Ⅰ型', '茂名干酪根-成熟 Easy%Ro=0.80', 'C204H269N3O12', '2017-Gao-Jump in the structure of Type I kerogen revealed from pyrolysis and 13C DP MAS NMR', '1.3186', '0.05882', '0.014705', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Gao Yuan', 'Ⅰ型', '茂名干酪根-接近油窗高峰期 Easy%Ro=0.90', 'C140H122N4O13', '2017-Gao-Jump in the structure of Type I kerogen revealed from pyrolysis and 13C DP MAS NMR', '0.8714', '0.092857', '0.02857', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Gao Yuan', 'Ⅰ型', '茂名干酪根-未熟 Easy%Ro=0.43', 'C248H36 N3O20', '2017-Gao-Jump in the structure of Type I kerogen revealed from pyrolysis and 13C DP MAS NMR', '1.4717', '0.0806', '0.01209', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Gao Yuan', 'Ⅰ型', '茂名干酪根-油窗后期 Easy%Ro=1.10', 'C208H168N4O10', '2017-Gao-Jump in the structure of Type I kerogen revealed from pyrolysis and 13C DP MAS NMR', '0.80769', '0.048076', '0.01923', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Gao Yuan', 'Ⅰ型', '茂名干酪根-油窗末期 Easy%Ro=1.30', 'C212H151N3O10', '2017-Gao-Jump in the structure of Type I kerogen revealed from pyrolysis and 13C DP MAS NMR', '0.71226', '0.047169', '0.0141509', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Huang Liang', 'Ⅰ-Ⅱ1型', '四川盆地志留系龙马溪组海相页岩干酪根', 'C194H96O9N4S7', 'Thermodynamic and Structural Characterization of Bulk Organic Matter in Chinese Silurian Shale: Experimental and Molecular Modeling Studies', '0.495', '0.046', '0.021', '0.036', 'overmature type II kerogen by Ungerer et al. (1.21−1.28 g/cm3).', '(360 K, 23.6 MPa) 下1.226-1.261 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', 'Wang Qian', 'Ⅲ型', '宜兰油页岩干酪根', 'C5322H6322O1355N100S45', '2017-Wang Qian-A study on the structure of Yilan oil shale kerogen based on its alkali-oxygen oxidation yields of benzene carboxylic acids, 13CNMR and XPS', '1.19', '0.26', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017', '刘向君', 'Ⅱ型', '四川盆地龙马溪组干酪根', 'C205H158O19N4S4（文章中是C206，但是根据分子式实际是C205）', '2017-刘向君-龙马溪组页岩干酪根平均分子结构模型的构建', '0.77', '0.093', '0.0195', '0.0195', '', '建立的二维干酪根模型中没有使用密度来验证模型，仅是利用核磁图谱相近以及结构参数接近而验证。');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017、2018', '王擎、程枫', 'Ⅰ-Ⅱ型，接近Ⅰ型', '抚顺干酪根', 'C240H346O19N8S3', '1、2017-王擎-油页岩干酪根化学键浓度与能量密度研究    2、2018-程枫-油页岩干酪根三维结构特性的分子模拟-硕士论文', '1.44', '0.079', '0.033', '0.0125', '实验 20℃-1.107 g/cm3', '在温度 20℃（293K）时为 1.065 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2017、2018', '王擎、程枫', 'Ⅰ-Ⅱ型，接近Ⅰ型', '茂名干酪根', 'C244H344O23N6S6', '1、2017-王擎-油页岩干酪根化学键浓度与能量密度研究   2、2018-程枫-油页岩干酪根三维结构特性的分子模拟-硕士论文', '1.4098', '0.943', '0.0246', '0.0246', '实验 20℃-1.098g/cm3', '在温度 20℃（293K）时为 1.032g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Berthonneau', 'Ⅱ型', '应用亮场电子层析成像技术对烃源岩有机质进行了三维重建，获得了亚纳米分辨率的有机孔隙网络。', '', 'Mesoscale structure, mechanics, and transport properties of source rocks’ organic pore networks', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Liang', 'Ⅱ型', '四川盆地下寒武统牛蹄塘组干酪根', 'C210H184O20N4S4', 'Microstructure and adsorption properties of organic matter in Chinese Cambrian gas shale: Experimental characterization, molecular modeling and molecular simulation', '0.88', '0.095', '0.019', '0.019', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Liang', 'Ⅱ型', '四川盆地龙马溪组干酪根', 'C205H158O19N4S4', '2018-Huang Liang-Enhanced gas recovery by CO2 sequestration in marine shale: a molecular view based on realistic kerogen model', '0.7707', '0.0923', '0.0195', '0.0195', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=0.76', 'C220H306N4O28S3', 'Chemical structure evolution of kerogen during oil generation', '1.3909', '0.012727', '0.01818', '0.01363', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=0.80', 'C209H296N2O12S', 'Chemical structure evolution of kerogen during oil generation', '1.416', '0.0574', '0.00956', '0.00478', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=0.94', 'C183H233NO16S', 'Chemical structure evolution of kerogen during oil generation', '1.2732', '0.0874', '0.00546', '0.00546', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=1.15', 'C159H145NO16S2', 'Chemical structure evolution of kerogen during oil generation', '0.911', '0.1', '0.006', '0.0125', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=1.38', 'C178H153NO14S', 'Chemical structure evolution of kerogen during oil generation', '0.859', '0.078', '0.0056', '0.0056', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=1.66', 'C192H133NO18S', 'Chemical structure evolution of kerogen during oil generation', '0.692', '0.093', '0.0052', '0.005', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Huang Zhenkai, Tian Liang，Li Maowen', 'Ⅱ型', '渤海湾盆地沾化凹陷Easy%Ro=1.98', 'C200H135NO22S', 'Chemical structure evolution of kerogen during oil generation', '0.675', '0.11', '0.005', '0.005', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Obliger', '成熟干酪根（实际是后沉积变质作用，属于过成熟干酪根，只不过用成熟来描述）', '使用淬火分子动力学方法模拟生成了未成熟和成熟的微孔干酪根模型（但是只考虑了C和H）', 'C9574H1040', 'Poroelasticity of methane-loaded mature and immature kerogen from molecular simulations', '0.109', '0', '0', '0', '1.1-1.4 g/cm3', '（模拟了不同温压下密度，但是对P、T对其影响很小）1.392 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Obliger', '未成熟Ⅰ型干酪根C8032 H8832（晚期成岩阶段的未成熟Ⅰ型干酪根，即接近未成熟/成熟过渡。）', '使用淬火分子动力学方法模拟生成了未成熟和成熟的微孔干酪根模型（但是只考虑了C和H）', 'C8032H8832', 'Poroelasticity of methane-loaded mature and immature kerogen from molecular simulations', '1.1', '0', '0', '0', '', 'the geological (400K, 25 MPa) density is around 0.94 g/cm3.');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Pan shuo', 'Ⅰ型', '龙口干酪根', 'C236H314O36N8S3', '1、2018-潘朔-Molecular Structure and Electronic Properties of Oil Shale Kerogen: An Experimental and Molecular Modeling Study       2、2020-潘朔-油页岩油母质分子结构及其热解反应过程的分子模拟-博士论文', '1.33', '0.15', '0.339', '0.0127', '1.02g/cm3', '1.01 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2018', 'Wang Qing', 'Ⅱ型', '窑街干酪根', 'C249H257O12N5S2', '2018-wang Qing-Experimental and dynamics simulation studies of the molecular modeling and reactivity of the Yaojie oil shale kerogen', '1.0321', '0.0482', '0.0281', '0.008', '1.09g/cm3', '1.10 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2019', 'Cao Jinrong ', 'Ⅲ型', '', 'C675H615O75N11S6', 'Molecular simulation of CH4 adsorption behavior in slit nanopores: Verification of simulation methods and models', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2019', 'Chu Wenying ', 'Ⅱ/Ⅰ型(2012,Ru；2011,Tong；2013，Orendt；2019-Chu, WenyⅠng)', '爱沙尼亚kukersite干酪根（基于2003，Lille的模型修改的）', 'C365H544O44NS3Cl（由两个独立的片段组成,画出后才知道）', 'Investigation into the Effect of Heteroatom Content on Kerogen Structure Using Advanced 13C Solid-State Nuclear Magnetic Resonance Spectroscopy', '1.4904', '0.1205', '0.0027', '0.0082', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2019', 'Wang Xiaohe', 'Ⅲ型', '鄂尔多斯盆地干酪根', 'C853H756N8O115S6', '2019-Wang Xiaohe-The Constructions and Pyrolysis of 3D Kerogen Macromolecular Models: Experiments and Simulations', '0.886', '0.1348', '0.00937', '0.00703', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2019', 'Wang Xiaohe', 'Ⅰ型', '松辽盆地干酪根', 'C612H846N10O40S7', '2019-Wang Xiaohe-The Constructions and Pyrolysis of 3D Kerogen Macromolecular Models: Experiments and Simulations', '1.382', '0.065', '0.0163', '0.011', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2019', 'Wangqing', 'Ⅰ型', '龙口油页岩', 'C236H314O36N8S3', 'Theoretical Study of Structural and Spatial Properties of Kerogen', '1.3305', '0.1525', '0.339', '0.0127', null, '1.3 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Atmani、Leyssale', 'Ⅲ型', '使用副本交换分子动力学模拟方法生成通过木质素形成成熟III型干酪根模型（深成热解阶段末期）', 'C1377H697O15', 'Simulating the Geological Fate of Terrestrial Organic Matter: Lignin vs Cellulose', '', '', '', '', '', '待细读');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Liang Tian, Yan-Rong Zou', 'Ⅰ型', '渤海湾盆地东营凹陷Easy%Ro=0.68', 'C204H288O17N2S', 'An evaluation of kerogen molecular structures during artificial maturation', '1.4117', '0.8333', '0.0098', '0.0049', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Liang Tian, Yan-Rong Zou', 'Ⅰ型', '渤海湾盆地东营凹陷Easy%Ro=0.80', 'C205H274O15N2S', 'An evaluation of kerogen molecular structures during artificial maturation', '1.3366', '0.0732', '0.0098', '0.0049', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Liang Tian, Yan-Rong Zou', 'Ⅰ型', '渤海湾盆地东营凹陷Easy%Ro=0.94', 'C169H195O15NS', 'An evaluation of kerogen molecular structures during artificial maturation', '1.1538', '0.0888', '0.0059', '0.0059', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Liang Tian, Yan-Rong Zou', 'Ⅰ型', '渤海湾盆地东营凹陷Easy%Ro=1.15', 'C152H140O23N2S2', 'An evaluation of kerogen molecular structures during artificial maturation', '0.9211', '0.1513', '0.0132', '0.0132', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Liang Tian, Yan-Rong Zou', 'Ⅰ型', '渤海湾盆地东营凹陷Easy%Ro=1.38', 'C149H114O21N2S2', 'An evaluation of kerogen molecular structures during artificial maturation', '0.7651', '0.1409', '0.0134', '0.0134', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Liang Tian, Yan-Rong Zou', 'Ⅰ型', '渤海湾盆地东营凹陷Easy%Ro=1.66', 'C148H101O20NS2', 'An evaluation of kerogen molecular structures during artificial maturation', '0.6824', '0.1351', '0.0068', '0.135', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020', 'Zhang zhijun', 'Ⅰ型', '龙口油页岩', 'C340H481O41N5S6', 'A ReaxFF molecular dynamics study on the mechanism and the typical pyrolysis gases\r\nin the pyrolysis process of Longkou oil shale kerogen', '1.4147', '0.1176', '0.0147', '0.0176', null, '0.94 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2020、2022', 'Pan shuo', 'Ⅰ型', '桦甸油页岩干酪根', 'C233H357O25N3S3', '1、2020-潘朔-油页岩油母质分子结构及其热解反应过程的分子模拟-博士论文       2、2022-Pan shuo-Experimental and Molecular Simulation Studies of Huadian Oil Shale Kerogen', '1.532188', '0.107296', '0.0128755', '0.0128755', '0.97g/cm3', '0.95 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Cao Huairen', 'Ⅰ型', '松辽盆地青山口组- Easy%Ro=0.49', 'C168H285O12N3', 'Molecular structure evolution of Type I kerogen during pyrolysis: Case study from the Songliao Basin, NE China', '1.6964', '0.0714285', '0.017857', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Cao Huairen', 'Ⅰ型', '松辽盆地青山口组Easy%Ro=1.18', 'C156H159O10N3', 'Molecular structure evolution of Type I kerogen during pyrolysis: Case study from the Songliao Basin, NE China', '1.0192307', '0.06410256', '0.0192307', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Cao Huairen', 'Ⅰ型', '松辽盆地青山口组Easy%Ro=1.76', 'C123H107O7N5', 'Molecular structure evolution of Type I kerogen during pyrolysis: Case study from the Songliao Basin, NE China', '0.8699', '0.0569105', '0.0406504', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Cao Huairen', 'Ⅰ型', '松辽盆地青山口组Easy%Ro=2.5', 'C150H111O4N3', 'Molecular structure evolution of Type I kerogen during pyrolysis: Case study from the Songliao Basin, NE China', '0.74', '0.02666', '0.02', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Liu Yu ', 'Ⅱ型', '美国Marcellus油页岩干酪根Ro = 1.5%', 'C204H178O38N4', 'The molecular model of Marcellus shale kerogen: Experimental characterization and structure reconstruction', '0.8725', '0.186', '0.0206', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Wang Xiaoye', 'Ⅰ型', '桦甸大城子油页岩干酪根', 'C477H750O48', 'Structural characterization of Huadian oil shale kerogen by using 13C DP/MAS NMR', '1.572', '0.101', '0', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'Zhang Zhijun', 'Ⅱ型', '龙口干酪根', 'C341H481O40N5S6 ', '2021-Zhang Zhijun-Structural model of Longkou oil shale kerogen and the evolution process under steam pyrolysis based on ReaxFF molecular dynamics simulation（参考2015-Guan的构建模型规则来的）', '1.4106', '0.1173', '0.0147', '0.0176', '', '建立的二维干酪根模型中没有使用密度来验证模型，仅是利用核磁图谱相近而验证。');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'ZhangChu', 'Ⅲ型', '鄂尔多斯盆地山西组', 'C137H95O5N3', 'Microstructure characterization of kerogen in mature shale: Molecular \r\ninvestigation of micropore development', '0.6934', '0.0365', '0.0219', '0', null, '1.16 g/cm3 ');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021', 'ZhangChu', 'Ⅱ型', 'Marcellus干酪根', 'C177H177O10N9S5', 'Microstructure characterization of kerogen in mature shale: Molecular \r\ninvestigation of micropore development', '1', '0.0565', '0.0508', '0.0282', null, '1.04 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2021、2022', 'Kang Dongliang', '', '机器学习预测干酪根的1/4-1/8及基于前人建立的干酪根模型及产物片段预测类型成熟度', 'C35H34O7', '1、Predicting the components and types of kerogen in shale by combining machine learning with NMR spectra           2、Predicting the Molecular Models, Types, and Maturity of Kerogen in Shale Using Machine Learning and Multi-NMR Spectra', '', '', '', '', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Huang Shan', 'Ⅰ型', '四川盆地志留系龙马溪组深部含气页岩干酪根', 'C320H263O19N7S2', 'Experimental characterization and molecular modeling ofkerogen in Silurian deep gas shale from southern Sichuan Basin, China', '0.8219', '0.0594', '0.0219', '0.0063', '', '1.19 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Wang Qing', 'Ⅱ型', '抚顺干酪根', 'C240H322O32N7S5（设计了12个不同的网格的同分异构体，最终选择FS7模型）', '1、2022-Wang Qing-The three-dimensional molecular structure model of Fushun oil shale kerogen, China     2、2023-Wang Xinmin , Wang Qing -The non-isothermal thermal decomposition evolution of the Fushun oil shale kerogen based on ReaxFF molecular dynamics simulation', '1.34166', '0.13333', '0.0291666', '0.0208333', '实验293 K，1.107 g/cm3', '1.072  g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Wang Xiaoye', 'Ⅰ型', '桦甸大城子油页岩干酪根', 'C487H778O43N8S5', 'Three-dimensional molecular modeling of Dachengzi oil shale kerogen', '1.598', '0.088', '0.016', '0.01', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Wu Ziheng', 'Ⅱ型', '鄂尔多斯盆地长7段干酪根', 'C300H297O18N13S10', '2022-Wu-Experimental and molecular dynamics investigation on the pyrolysis mechanism of Chang 7 type-II oil shale kerogen', '0.99', '0.06', '0.0433', '0.0333', '', '模拟密度增加至1.0g/cm3，这与长7油页岩干酪根的实际密度非常一致。');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Zhang Chu', 'Ⅱ型', '四川盆地城口地区罗江段LJ龙马溪组干酪根Ro = 1.27%', 'C227H205O18N15S17', '1、Heterogeneous development of micro- and meso-pores in shale kerogen: New insights from chemical structure analysis      2、Combined effects of the chemical structure and nanopore development on water vapor/liquid adsorption in shale kerogen', '0.903', '0.079', '0.0661', '0.0749', '0.98 g/cm3', '1.04 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Zhang Chu', 'Ⅱ型', '四川盆地石柱地区七寮段QL龙马溪组干酪根Ro = 2.93%', 'C169H126O7N2S3', '1、Heterogeneous development of micro- and meso-pores in shale kerogen: New insights from chemical structure analysis      2、Combined effects of the chemical structure and nanopore development on water vapor/liquid adsorption in shale kerogen', '0.746', '0.041', '0.0118', '0.0178', '1.21-1.28 g/cm3', '1.2 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Zhao Fumin', 'Ⅰ型', '抚顺干酪根Ⅰ', 'C228H350O10N6S3', 'Chemical structure characteristics and multidimensional model\r\nconstruction of Fushun oil shale kerogen: An experimental and\r\nsimulation study', '1.535087', '0.0438596', '0.026315789', '0.01315789', '', '0.943 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Zhao Fumin', 'Ⅰ型', '抚顺干酪根Ⅱ', 'C228H350O10N6S3', 'Chemical structure characteristics and multidimensional model\r\nconstruction of Fushun oil shale kerogen: An experimental and\r\nsimulation study', '1.535087', '0.0438596', '0.026315789', '0.01315789', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Zhao Fumin', 'Ⅰ型', '抚顺干酪根Ⅲ', 'C228H346O10N6S3', 'Chemical structure characteristics and multidimensional model\r\nconstruction of Fushun oil shale kerogen: An experimental and\r\nsimulation study', '1.5175', '0.0438596', '0.026315789', '0.01315789', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2022', 'Zhao Fumin', 'Ⅰ型', '抚顺干酪根Ⅳ', 'C228H346O10N6S3', 'Chemical structure characteristics and multidimensional model\r\nconstruction of Fushun oil shale kerogen: An experimental and\r\nsimulation study', '1.5175', '0.0438596', '0.026315789', '0.01315789', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Hou Dali', 'Ⅱ型', '四川盆地龙马溪组露头样品', 'C237H219O21N5S4', 'Characterization of kerogen molecular structure and its effect on methane adsorption behavior: A comparative study on outcrop and core samples from Longmaxi shale', '0.9241', '0.886', '0.0211', '0.0169', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Huo Dali', 'Ⅲ型', '四川盆地龙马溪组岩心样品', 'C238H171O27N5S4', 'Characterization of kerogen molecular structure and its effect on methane adsorption behavior: A comparative study on outcrop and core samples from Longmaxi shale', '0.7185', '0.1134', '0.021', '0.0168', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Kanyuan Shi', 'Ⅱ型', 'Nanpu shale 干酪根', 'C199H240O20N6S2', 'Average molecular structure model of shale kerogen: Experimental characterization, structural reconstruction, and pyrolysis analysis', '1.2060', '0.1005', '0.0302', '0.0101', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Liang Tian , Zhan Zhao-Wen', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组Easy%Ro=0.45', 'C207H325O4NS', 'Research on type I kerogen molecular simulation and docking between kerogen and saturated hydrocarbon molecule during oil generation', '1.57', '0.0193', '0.0048', '0.0048', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Liang Tian , Zhan Zhao-Wen', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组Easy%Ro=0.56', 'C204H299O5NS', 'Research on type I kerogen molecular simulation and docking between kerogen and saturated hydrocarbon molecule during oil generation', '1.4657', '0.0245', '0.0049', '0.0049', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Liang Tian , Zhan Zhao-Wen', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组Easy%Ro=0.75', 'C213H283O4NS', 'Research on type I kerogen molecular simulation and docking between kerogen and saturated hydrocarbon molecule during oil generation', '1.3286', '0.0188', '0.0047', '0.0047', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Liang Tian , Zhan Zhao-Wen', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组Easy%Ro=0.95', 'C169H147O4NS', 'Research on type I kerogen molecular simulation and docking between kerogen and saturated hydrocarbon molecule during oil generation', '0.8698', '0.0237', '0.0059', '0.0059', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Liang Tian , Zhan Zhao-Wen', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组Easy%Ro=1.27', 'C173H111O4NS', 'Research on type I kerogen molecular simulation and docking between kerogen and saturated hydrocarbon molecule during oil generation', '0.6416', '0.0231', '0.0058', '0.0058', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Y.zhou', 'Ⅱ型', '鄂尔多斯盆地长7段干酪根K1', 'C300H298O20N12S8', 'Molecular and experimental study on hydrogen sulfide formation mechanism during Chang 7 type-II oil shale kerogen py', '0.9933', '0.0667', '0.04', '0.0267', '', '1.01 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Y.zhou', 'Ⅱ型', '鄂尔多斯盆地长7段干酪根K2', 'C300H334O20N12S8', 'Molecular and experimental study on hydrogen sulfide formation mechanism during Chang 7 type-II oil shale kerogen py', '1.1133', '0.0667', '0.04', '0.0267', '', '1.03 g/cm³');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Y.zhou', 'Ⅱ型', '鄂尔多斯盆地长7段干酪根K3', 'C300H297O20N11S8', 'Molecular and experimental study on hydrogen sulfide formation mechanism during Chang 7 type-II oil shale kerogen py', '0.99', '0.0667', '0.3667', '0.0267', '', '1.03 g/cm³');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Zhang Deping, Cao Huairen', 'Ⅱ型', '松辽盆地嫩江组Easy%Ro=0.67', 'C164H272O18N4', 'A study on molecular structural evolution of type II kerogen in a gold tube thermal system: Insights from solid-state 13C NMR', '1.6585', '0.1097', '0.02439', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Zhang Deping, Cao Huairen', 'Ⅱ型', '松辽盆地嫩江组Easy%Ro=0.89', 'C94H124O8N4', 'A study on molecular structural evolution of type II kerogen in a gold tube thermal system: Insights from solid-state 13C NMR', '1.319', '0.085', '0.0425', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Zhang Deping, Cao Huairen', 'Ⅱ型', '松辽盆地嫩江组Easy%Ro=1.18', 'C109H118O9N4', 'A study on molecular structural evolution of type II kerogen in a gold tube thermal system: Insights from solid-state 13C NMR', '1.0825', '0.0825', '0.0366', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Zhang Deping, Cao Huairen', 'Ⅱ型', '松辽盆地嫩江组Easy%Ro=1.76', 'C129H98O11N6', 'A study on molecular structural evolution of type II kerogen in a gold tube thermal system: Insights from solid-state 13C NMR', '0.7596', '0.085', '0.0465', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Zhao Fumin ', 'Ⅱ型', 'Barkol kerogen', 'C252H277O13N7S2', 'The mechanism of H2O in the superheated steam affecting the quality of in-situ pyrolysates of oil shale kerogen: Part B-favorable conversion of residues', '1.0992', '0.0516', '0.0278', '0.0079', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', 'Zhao Fumin ', 'Ⅱ型', 'Barkol kerogen(N和S替换为C或O )', 'C260H287O15', 'The mechanism of H2O in the superheated steam affecting pyrolysis of the kaolinite-associated kerogen', '1.1038', '0.0577', '0', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', '张彤', 'Ⅲ型', '北龙马溪组页岩干酪根LZ-1', 'C173H151O24N9', '渝东北龙马溪组页岩干酪根微孔发育模式及其甲烷吸附效应', '0.8728', '0.1387', '0.052', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', '张彤', 'Ⅲ型', '北龙马溪组页岩干酪根SQ-6', 'C178H114O13N4S', '渝东北龙马溪组页岩干酪根微孔发育模式及其甲烷吸附效应', '0.6404', '0.073', '0.0225', '0.0056', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2023', '张彤', 'Ⅲ型', '北龙马溪组页岩干酪根TB-27', 'C161H105O37N5', '渝东北龙马溪组页岩干酪根微孔发育模式及其甲烷吸附效应', '0.6522', '0.2298', '0.0311', '0', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', 'Changrong Li', 'Ⅱ1型', '长7页岩干酪根Model W-2', 'C208H209O10N5S7', 'Thermodynamic and microstructural properties of the lacustrine Chang-7 shale kerogen: Implications for in-situ conversion of shale', '1.0048', '0.0481', '0.0240', '0.0337', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', 'Changrong Li', 'Ⅱ1型', '长7页岩干酪根Model Y-2', 'C228H276O17N6S14', 'Thermodynamic and microstructural properties of the lacustrine Chang-7 shale kerogen: Implications for in-situ conversion of shale', '1.2105', '0.0746', '0.0263', '0.0614', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', 'Changrong Li', 'Ⅰ型', '长7页岩干酪根Model Y-1', 'C229H283O14N5S14', 'Thermodynamic and microstructural properties of the lacustrine Chang-7 shale kerogen: Implications for in-situ conversion of shale', '1.2358', '0.0611', '0.0218', '0.0611', '', '');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', 'Han Xiangxin', 'Ⅰ型', '桦甸干酪根', 'C392H672O30N2S2', 'Thermal decomposition of Huadian oil shale: Part 2. The role of bonds in the kerogen skeleton chain during pyrolysis evaluated by ReaxFF MD simulations', '1.7143', '0.0765', '0.005', '0.005', null, '1.0');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', 'Jing Liu', 'Ⅰ型', '龙马溪组', 'C151H86O13N2', 'Molecular Structural Characteristics and 3D Model Reconstruction of\r\nOrganic Matter in Longmaxi Formation Shale', '0.539', '0.079', '0.013', '0', null, '1.77 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', '刘攀', 'Ⅲ型', '龙马溪组', 'C244H108O32N4S5', '中浅层页岩干酪根化学组成与结构特性', '0.4426', '0.1311', '0.01639', '0.02049', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', '施砍园', 'Ⅱ型', '渤海湾盆地南堡凹陷沙三段', 'C199H240O20N6S2', 'Average molecular structure model of shale kerogen: Experimental characterization, structural reconstruction, and pyrolysis analysis', '1.2060', '0.1005', '0.0302', '0.01001', null, '1.106 ');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', '郭成波', 'Ⅱ型', '前寒武系下马岭组', 'C278H346O26N7S15', '典型II型干酪根分子模型构建及热解分子模拟研究', '1.245', '0.094', '0.022', '0.007', null, '1.067 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', '郭成波', 'Ⅱ型', '瑞典寒武系Alum页岩', 'C270H318O39N8S14', '典型II型干酪根分子模型构建及热解分子模拟研究', '1.178', '0.144', '0.030', '0.052', null, '1.077 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2024', '郭成波', 'Ⅱ型', '鄂尔多斯盆地延长组长7段', 'C239H259O28N9S13', '典型II型干酪根分子模型构建及热解分子模拟研究', '1.084', '0.117', '0.038', '0.054', null, '1.179 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2025', 'Lijia Xiong', 'Ⅰ型', '北票干酪根', 'C345H506O34N10S19', 'Macromolecular structure and model of Beipiao oil shale kerogen as well as  comparison with those of other kerogens', '1.47', '0.098', '0.029', '0.055', null, null);
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2025', 'Youjie Li', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组D-1', 'C305H440O11N6S', 'Multiscale Elucidation of kerogen heterogeneity in Lucaogou Formation based on experiment and simulation: Structural Determinants of reactivity and stability for shale oil conversion', '1.443', '0.0361', '0.0197', '0.00328', '1.149 g/cm3', '0.951 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2025', 'Youjie Li ', 'Ⅰ型', '准噶尔盆地吉木萨尔凹陷芦草沟组U-2', 'C304H502O20N10S ', 'Multiscale Elucidation of kerogen heterogeneity in Lucaogou Formation based on experiment and simulation: Structural Determinants of reactivity and stability for shale oil conversion', '1.651', '0.0658', '0.0329', '0.00329', '1.245 g/cm3', '0.971 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2025', '宋银海', 'Ⅱ型', '鄂尔多斯盆地延长组长7段', 'C225H241O16N7S15', 'Constructing the 3D Molecular Structure of Lacustrine Kerogen from the Triassic Chang 7 Member, Ordos Basin (West China)', '1.07', '0.07', '0.031', '0.067', '', '1.177 g/cm3');
INSERT INTO `api_kerogenmodel`("year","author","kerogen_type","kerogen_name","Kerogen_shale_molecular_formula","literature_source","model_element_ratio_H_C","model_element_ratio_O_C","model_element_ratio_N_C","model_element_ratio_S_C","experimental_kerogen_density","simulated_kerogen_density") VALUES ('2025', '马桂丽', 'Ⅰ型', '渤海湾盆地辽河坳陷西部凹陷古近系沙河街组\r\n渤海湾盆地辽河坳陷西部凹陷古近系沙河街组\r\n渤海湾盆地辽河凹陷西部古近系沙河街组', 'C188H310O14N4S', '渤海湾盆地辽河坳陷西部凹陷曙光地区古近系沙河街低熟页岩干酪根分子结构及生烃特征\r\n渤海湾盆地辽河坳陷西部凹陷曙光地区古近系沙河街低熟页岩干酪根分子结构及生烃特征\r\n渤海湾盆地辽河坳陷西部凹陷曙光地区古近系沙河街低熟页岩干酪根分子结构及生烃特征', '1.649', '0.074', '0.021', '0.005', '1.1165 g/cm3', '1.1109 g/cm3');
